name: Calling Hello World Reusable Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  use-hello-world-workflow:
    uses: app63/github-resuable-workflows/.github/workflows/hello-world-reusable.yml@main
    with:
      name: "GitHub Actions"
  
  print-output:
    runs-on: ubuntu-latest
    needs: use-hello-world-workflow
    steps:
      - name: Print Output
        run: |
          echo "OUTPUT: ${{ needs.use-hello-world-workflow.outputs.message }}"
          echo "================== ENVIRONMENT =================="
          env
          echo "================== END =================="
